<script src="<?= base_url('assets/libs/jquery/dist/jquery.min.js'); ?>"></script>
<script src="<?= base_url('assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js'); ?>"></script>
<script src="<?= base_url('assets/js/sidebarmenu.js'); ?>"></script>
<script src="<?= base_url('assets/js/app.min.js'); ?>"></script>
<script src="<?= base_url('assets/libs/simplebar/dist/simplebar.js'); ?>"></script>
<script src="<?= base_url('plugins/datatables/datatables.min.js'); ?>"></script>
<script src="<?= base_url('plugins/jquery-mask/jquery.mask.js'); ?>"></script>
<script src="<?= base_url('plugins/select2/js/select2.min.js'); ?>"></script>
<script src="<?= base_url('plugins/chart.js/Chart.min.js'); ?>"></script>